# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="ArchiveTeam seesaw kit"
HOMEPAGE="http://www.archiveteam.org/"
SRC_URI="https://pypi.python.org/packages/source/s/seesaw/${P}.tar.gz"

LICENSE=""
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/tornadio2-0.0.3
	>=dev-python/tornado-2.3
	dev-python/ordereddict
	dev-python/setuptools"
#	dev-python/argparse


