# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="Simple, fast, extensible JSON encoder/decoder for Python"
HOMEPAGE="http://github.com/simplejson/simplejson"
SRC_URI="https://pypi.python.org/packages/source/s/simplejson/${P}.tar.gz"

LICENSE="AFL-3.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""



