# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="A drop-in substitute for Py2.7's new collections.OrderedDict that works in Python 2.4-2.6."
HOMEPAGE="UNKNOWN"
SRC_URI="https://pypi.python.org/packages/source/o/ordereddict/${P}.tar.gz"

LICENSE=""
KEYWORDS="~amd64"
SLOT="0"
IUSE=""



