# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils

MY_PN="TornadIO2"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Socket.io 0.7+ server implementation on top of Tornado framework"
HOMEPAGE="http://github.com/MrJoes/tornadio2/"
SRC_URI="https://pypi.python.org/packages/source/T/TornadIO2/${MY_P}.tar.gz"

LICENSE=""
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/simplejson-2.1.0
	>=dev-python/tornado-2.2.0
	dev-python/setuptools"

S="${WORKDIR}/${MY_P}"

